name: farm_wise
description: "final project for GP"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  table_calendar: ^3.0.9
  image_picker: ^1.1.2
  standard_searchbar: ^2.0.0
  dio: ^5.8.0+1
  icons_flutter: ^0.0.5
  vector_math: ^2.1.4
  vm_service: ^14.2.5
  http: ^1.2.0
  weather: ^3.2.1
  intl: ^0.20.2
  provider: ^6.1.5
  geolocator: ^10.0.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  internet_connection_checker_plus: ^2.7.2
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.2
  flutter_facebook_auth: ^7.1.1
  path_provider: ^2.1.5  # For file handling
  path: ^1.9.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/Image/
     - assets/AI/